src/Entity/Ad.php
<?php

namespace App\Entity;

use App\Repository\AdRepository;
use App\Entity\User;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: AdRepository::class)]
/**
 * @ORM\Entity(repositoryClass= "App\Repository\AdRepository")
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 *  fields={"title"},
 *  message="Une Autre annonce possede deja ce titre, Merci de le modifier"
 * )
 */
class Ad
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column]
    private ?float $price = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $introduction = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column(length: 255)]
    private ?string $coverImage = null;

    #[ORM\Column]
    private ?int $rooms = null;

    #[ORM\OneToMany(mappedBy: 'ad', targetEntity: Image::class, orphanRemoval: true)]
    private Collection $images;

    #[ORM\ManyToOne(inversedBy: 'ads')]
    private ?User $author = null;

    #[ORM\OneToMany(mappedBy: 'ad', targetEntity: Booking::class)]
    private Collection $bookings;

    #[ORM\OneToMany(mappedBy: 'ad', targetEntity: Comment::class, orphanRemoval: true)]
    private Collection $comments;

    
    

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->bookings = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    /**
     * Permet d'initialiser le slug!
     * 
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * 
     * @return void
     */
    public function initializeSlug() {
        if(empty($this->slug)) { 
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }


    /**
     * Permet de recuperer le commentaire d'un autheur par repport a une annonce
     * 
     * @param User $author
     * @return Comment|null
     */
    public function getCommentFromAuthor( User $author){
        foreach($this->comments as $comment){
            if($comment->getAuthor() === $author) return $comment;
        }
        return null;
    }

    /**
     * Permet d'optenir la moyanne globale des notes pour cette annonce
     * 
     * @return float
     */
    public function getAvgRatings(){
        //calculer la somme des notations
        $sum = array_reduce($this->comments->toArray(), function($total,$comment){
            return $total + $comment->getRating();
        }, 0);
        //Faire la division pour avoir la moyenne
        if(count($this->comments) > 0) return $sum / count($this->comments);
        return 0;
    }



    /**
     * Permet d'obtenir un tableau des jours qui sont ne sont pas disponibles pour cette annonce
     * 
     * @return array Un tableau d'objets DateTime representant les jours d'occupation
     * 
     */
    public function getNotAvailableDays(){
        $notAvailableDays = [];
        foreach($this->bookings as $booking){
            //Calculer les jours qui se trouvent entre la date d'arrivee et la date de depart
            $resultat = range(
                $booking->getStartDate()->getTimestamp(),
                $booking->getEndDate()->getTimestamp(),
                24 * 60 * 60 
            );

            $days = array_map(function($dayTimestamp){
                return new \DateTime(date('Y-m-d', $dayTimestamp));
            }, $resultat);

            $notAvailableDays = array_merge($notAvailableDays, $days); 
        }
        return  $notAvailableDays;

    }

     public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }


    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    public function getRooms(): ?int
    {
        return $this->rooms;
    }

    public function setRooms(int $rooms): self
    {
        $this->rooms = $rooms;

        return $this;
    }

    /**
     * @return Collection<int, Image>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setAd($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getAd() === $this) {
                $image->setAd(null);
            }
        }

        return $this;
    }


    public function __toString() {
        return $this->getTitle();
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection<int, Booking>
     */
    public function getBookings(): Collection
    {
        return $this->bookings;
    }

    public function addBooking(Booking $booking): self
    {
        if (!$this->bookings->contains($booking)) {
            $this->bookings->add($booking);
            $booking->setAd($this);
        }

        return $this;
    }

    public function removeBooking(Booking $booking): self
    {
        if ($this->bookings->removeElement($booking)) {
            // set the owning side to null (unless already changed)
            if ($booking->getAd() === $this) {
                $booking->setAd(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Comment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setAd($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getAd() === $this) {
                $comment->setAd(null);
            }
        }

        return $this;
    }

   
}

src/Form/AdType.php
<?php

namespace App\Form;

use App\Entity\Ad;
use App\Form\ApplicationType;
use Symfony\Component\Form\AbstractType;
use App\Form\ImageType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\MoneyType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;




class AdType extends ApplicationType
{

    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, $this->getConfiguration("Titre", "Tapez un super titre pour votre annonce"))
            ->add('coverImage', UrlType::class, $this->getConfiguration("Url de l'image principale", "Donner l'adress d'une image qui donne vraiment envie"))
            ->add('introduction', TextType::class, $this->getConfiguration("Introduction", "Donner une annonce globale de l'annonce",[
                'required' => false
            ]))
            ->add('content', TextareaType::class, $this->getConfiguration("Description detaillee", "Tapez une description qui donne vraiment envie de venir chez vous!"))
            ->add('rooms', IntegerType::class, $this->getConfiguration("Nombre de chambres", "Le nombre de chambres disponibles"))
            ->add('price', MoneyType::class, $this->getConfiguration("prix de nuit", "Indiquez le prix que vous voulez pour une nuit"))
            ->add('images', CollectionType::class, 
              [
                'entry_type' => ImageType::class,
                'allow_add' => true,
                'allow_delete' => true

              ]
            )

        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Ad::class,
        ]);
    }
}

src/Controller/AdController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use App\Entity\Ad;
use App\Form\AdType;
use App\Entity\Image;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\AdRepository;
use App\Repository\ImageRepository;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\HttpFoundation\Request;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;




class AdController extends AbstractController
{
    /**
     *  @Route("/ads", name= "ads_index")
     */
   
    public function index(AdRepository $repo): Response
    {

        //$repo = $this->getDoctrine()->getRepository(Ad::class);
        $ads = $repo->findAll();
        return $this->render('ad/index.html.twig', [
            'ads' => $ads
        ]);
    }

     /**
     * permet de creer une annonce
     * 
     * @Route("ads/new", name="ads_create")
     *
     * @IsGranted("ROLE_USER")
     * @return Response
     */

    public function create(Request $request,  AdRepository $adRepository, EntityManagerInterface $manager){


        $ad = new Ad();

        $form = $this->createForm(AdType::class, $ad);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
              foreach($ad->getImages() as $image){
                $image->setAd($ad);
                $manager->persist($image);
            }

            $ad->setAuthor($this->getUser());

            $manager->persist($ad);
            $manager->flush();
           $this->addFlash(
            'success',
            "L'annonce <strong>{$ad->getTitle()}</strong> a bien été enregistrées !"
        );

          
           return $this->redirectToRoute('ads_show',[
            'id' => $ad->getid()
           ]);
        }

        return $this->render('ad/new.html.twig',[
            'form' => $form->createView()
        ]);
    }

    /**
     * Permet d'afficher le furmulaire d'edition
     * 
     * @Route("/ads/{id}/edit", name="ads_edit")
     * @Security("is_granted('ROLE_USER') and user== ad.getAuthor()", message="Cette annonce ne vous appartient pas, vous ne pouvez pas la modifier")
     * @return Response
     */

    public function edit(Ad $ad, Request $request, AdRepository $adRepository, EntityManagerInterface $manager){

        $form = $this->createForm(AdType::class, $ad);
        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid()){
            foreach($ad->getImages() as $image){
              $image->setAd($ad);
              $manager->persist($image);
          }
          $manager->persist($ad);
          $manager->flush();

         $this->addFlash(
          'success',
          "Les Modifications de l'annonce <strong>{$ad->getTitle()}</strong> ont bien été enregistrées !"
      );

        
         return $this->redirectToRoute('ads_show',[
          'id' => $ad->getid()
         ]);
      }

       return $this->render('ad/edit.html.twig', [
        'form' => $form->createView(),
        'ad' => $ad
       ]);
        
       
    }




    /**
     * permet d'afficher une seule annonce
     * 
     * @Route("/ads/{id}", name="ads_show")
     * 
     * @return Response
     */
    public function show(Ad $ad){
        return $this->render('ad/show.html.twig' ,[
             'ad' => $ad
        ]);

    }

    /**
     * Permet de suuprimer une annonce
     * 
     * @Route("/ads/{id}/delete", name="ads_delete")
     * @Security("is_granted('ROLE_USER') and user == ad.getAuthor()", message="Vous n'avez pas 
     * le droit d'acceder a cette resource")
     * @param Ad $ad
     * @param ObjectManager $manager
     * @return Response
     */
    public function delete(Ad $ad, EntityManagerInterface $manager){
        $manager->remove($ad);
        $manager->flush();

        $this->addflash(
            'success',
            "L'annonce <strong>{$ad->getTitle()}</strong> a bien ete supprimee !"
        );
        return $this->redirectToRoute('ads_index');

    }

   
    
}

templates/ad/_ad.html.twig
{% set url = path('ads_show', {'id': ad.id}) %}
       
       <div class="col-md-4">
           <div class="card bg-light mb-3">
               <div class="card-header text-center">
                   {{ ad.rooms}} chambres, <strong>{{ ad.price |number_format(2,',',' ')}}DH / nuit</strong> <br>

                   {% if ad.comments|length > 0 %}
                        {% include 'partials/rating.html.twig' with {'rating': ad.avgRatings} %}
                   {% else %}
                   <small>Pas encore note</small>
                   {% endif %}
               </div>
               <a href="{{ url }}">
               <img src="{{ ad.coverImage }}" alt="Image de L'appartemant"
               style="height: 200px; width: 100%; display: block">
                </a>
               <div class="card-body">
                   <h4 class="card-title">
                   <a href="{{ url }}">
                    {{ ad.title}}
                   <a/>
                   </h4>
                   <p class="card-text">
                     {{ ad.introduction }}
                   </p>
                   <a href="{{ url }}" class="btn btn-primary float-right">En savoir plus !<a/>

                   {% if app.user and app.user == ad.author %}
                   <a href="{{ path('ads_edit',{'id': ad.id})}}" 
                   class="btn btn-secondary">Modifier l'annonce</a>
                    <a href="{{ path('ads_delete',{'id': ad.id})}}" 
                   class="btn btn-danger my-2" onclick="return confirm('Etes vous sur de vouloir supprimer l'annonce : {
                    {ad.title}}?')">Supprimer l'annonce</a>

                   {% endif %}


               </div>
           </div>
       </div>

templates/ad/collection.html.twig
{% block _ad_images_widget %}
 
 <p> Ici, Vous pouvez ajouter vos propres images !</p>

  {{ form_widget(form)}}

  <div class="form-group">
    <button type="button" id="add-image" class="btn btn-primary">Ajouter une image</button>
  </div>
{% endblock %}

{% block _ad_images_entry_row %}

{{ form_widget(form)}}
<input type="hidden" id="widgets-counter" value="0"> 

{% endblock %}



{% block _ad_images_entry_widget %}

<div class="form-group" id="block_{{id}}">

  <div class="row">
     <div class="col-10">
      <div class="row">
       <div class="col">
            {{ form_widget(form.url) }}
       </div>
       <div class="col">
            {{ form_widget(form.caption)}}
       </div>
    </div>
  </div>
  

  <div class="col-2">
  
  <button type="button" data-ation="delete" data-target="#block_{{id}}" class="btn btn-danger">X</button>
  </div>
</div>
</div>
{% endblock %}

templates/ad/edit.html.twig
{% extends 'base.html.twig'%}

{% block title %} Edition d'une Annonce {% endblock %}

 {% form_theme form 'ad/collection.html.twig' %}

{% block body %}
<div class="container">
    <h1> Modifier L'annonce: {{ad.title}} </h1>

    {{ form_start(form) }}

    {{ form_widget(form)}}

    <button type="submit" class="btn btn-primary">Enregistrer les modifications</button>

    {{ form_end(form) }}
 </div>

{% endblock %}

{% block javascripts %}

<script src="/js/ad.js"></script>


{% endblock %}

templates/ad/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos magnifiques annonces!{% endblock %}

{% block body %}
<div class="container">
     <h1 class="my-5"> Voici les annonces de nos hotels! </h1>

     <div class="row">
     {% for ad in ads %} 
       {% include 'ad/_ad.html.twig'%}

     {% endfor %}
     
     </div>
</div>
{% endblock %}

templates/ad/new.html.twig
{% extends 'base.html.twig'%}

{% block title %} Creation D'une Annonce {% endblock %}

 {% form_theme form 'ad/collection.html.twig' %}

{% block body %}

 <div class="container">
    <h1> Creer une nouvelle annonce </h1>

    {{ form_start(form) }}

    {{ form_widget(form)}}

    <button type="submit" class="btn btn-primary">Creer la nouvelle announce</button>

    {{ form_end(form) }}
 </div>



{% endblock %}


{% block javascripts %}

<script src="/js/ad.js"></script>


{% endblock %}

templates/ad/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
{{ad.title}}
{% endblock %}


{% block body %}

<div class="ad.title" style="background-image: url({{ ad.coverImage }}); height: 30em;
    width: 650px;
    margin-left: 100px;">
 <div class="container">
 <h1>{{ad.title}}</h1>
 <p>{{ad.introduction}}</p>
 <p class="h2">
 <strong>{{ad.rooms}} Chambres</strong> pour <strong>{{ad.price |number_format(2,',',' ')}}DH
 </strong> par nuit
 </p>
 <a href="{{ path('app_booking', {'id': ad.id}) }}" class="btn btn-primary">Reserver !</a>

 {% if app.user and app.user == ad.author %}
 <a href="{{ path('ads_edit',{'id': ad.id})}}" 
 class="btn btn-secondary">Modifier l'annonce</a>
 {% endif %}
 </div>
</div>

<div class="container">

       <div class="col-md-8 mb-3">
         {{ ad.content | raw }}  
        </div>
  <div class="carousel-inner">


<hr>

{% if ad.comments|length > 0 %}
  <h2 class="mb-3">Commentaire de nos voyageurs :</h2>

  <div class="alert alert-info">
    <h4 class="alert-heading text-center">
      <div class="row align-items-center">
        <div class="col">
          Note globale donnee par nos voyageurs 
      </div>
      <div class="col">
      {% include 'partials/rating.html.twig' with {'rating': ad.avgRatings} %}
      <br>
      <small>(Calculee sur {{ ad.comments|length}} avis)</small>

      </div>
      </div>
    </h4>
  </div>    



  {% for comment in ad.comments %}
    <div class="bg-light rounded mb-3 py-3 px-3">
      <strong>{{ comment.author.firstName}}</strong> a dit :
      <blockquote>
        {{comment.content}}
      </blockquote>
      <strong>Note donnée : </strong> 
      {% set rating = comment.rating %}
      {% include 'partials/rating.html.twig' with {'rating':
      comment.rating} %}
      </div>
  {% endfor %} 
{% else %}   
  <h2>Cette annonce n'a pas encore recu de commentaires ...</h2>
{% endif %}  
       
       <div class="col">
       {% set a = ad.author %}
         <div class="row mb-3 align-items-center">
           <div class="col-3">
           <a href="{{path ('app_user', {'id': a.id}) }}">
               <img src="{{a.picture}}" class="avatar avatar-medium" alt="Avatar de {{a.firstName}} {{a.lastName}}"> 
           </a>
           </div>
           <div class="col">
            <a href="{{path ('app_user', {'id': a.id}) }}">
             <h3>{{a.firstName}} {{a.lastName}}</h3>
            </a>
             <span class="badge badge-primary">{{a.ads | length}} annonces</span>
           </div>
         </div>
         {{a.description | raw }}

        </div>
    </div>
</div>




{% endblock %}